Sprint 7
2048-game-team/2048-game pull request #45
Opened 2023-02-28 11:38 UTC by DmitryLavrov

### Какую задачу решаем
Спринт 7 выполнен:
- SSR
- OAuth-авторизация
- Лидерборд
- Дополнительное Web-API (музыка)

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-28 11:42 UTC, kamenskiyyyy approved these changes

2023-03-01 09:32 UTC, shoom1337 requested changes

2023-03-01 09:41 UTC, kamenskiyyyy commented on .env.sample
> +DATABASE_URL="postgresql://postgres:postgres@localhost:5432/postgres"
странно, что сюда попала старая версия, мы исправили на переменные 👀

2023-03-01 14:18 UTC, DmitryLavrov commented on packages/client/src/entities/music/ui.ts
> +    if (volume <= 0.01) return;
Да, в AntD для компонента Slider при настройках по-умолчанию мы не доходим до нуля. Меня 0,01 тоже устраивает, и я не стал на этом останавливаться.

2023-03-01 14:21 UTC, DmitryLavrov commented on packages/client/src/pages/leaderboard/userBox/ui.tsx
> +    user?.display_name ?? `${user?.first_name} ${user?.second_name}`;
user - это локальный стейт 
`const [user, setUser] = useState<UserResponse>();`
При инициализации имеем undefined

2023-03-01 14:21 UTC, DmitryLavrov commented on packages/server/server.ts
> +    );
Спасибо за идею!
Возьмем на заметку.

2023-03-01 14:23 UTC, DmitryLavrov commented on packages/client/src/entities/game-drive/undoRedo/types.ts
> +}
Спасибо за информацию!

2023-03-01 14:25 UTC, DmitryLavrov commented on packages/client/src/pages/signin/yandexIcon/ui.tsx
> +  </svg>
Согласен. Подумаем.

2023-03-01 15:20 UTC, kamenskiyyyy commented on packages/client/src/entities/music/const.ts
> +};
А в чем смысл?

2023-03-01 17:55 UTC, shoom1337 approved these changes

2023-03-01 17:58 UTC, shoom1337 commented on packages/client/src/entities/music/const.ts
> +};
Чтобы лишний раз не пересобирать проект, если захочется в будущем поменять звук. 
Но тут не прям тот случай, когда 100% в энв. Просто просится какой-то механизм управления, когда вижу хардкод путей к файлам)

2023-03-01 17:59 UTC, kamenskiyyyy commented on packages/client/src/entities/music/const.ts
> +};
Файлы в любом случае лежат в public, значит нужно будте докер образ пересобирать

2023-03-01 18:01 UTC, kamenskiyyyy commented on packages/client/src/pages/game/undoRedoButtons/ui.tsx
> +  };
хорошее замечание

2023-03-01 18:03 UTC, kamenskiyyyy commented on packages/client/src/entities/music/ui.ts
> +    if (volume <= 0.01) return;
@DmitryLavrov может округлять просто? Сотые значения тут не думаю, что нужны

2023-03-01 18:18 UTC, kamenskiyyyy commented on packages/client/const.ts
> +export const YandexOAuthRedirectUri = 'http://localhost:3000';
перенесем

2023-03-01 18:34 UTC, shoom1337 commented on packages/client/src/entities/music/const.ts
> +};
public можно смапить через [volume](https://docs.docker.com/storage/volumes/), тогда пересобирать контейнер не нужно.

2023-03-01 18:40 UTC, kamenskiyyyy commented on packages/client/src/entities/music/const.ts
> +};
те тебе реально легче полезть руками на сервак, чтобы заменить там файл и не иметь в истории этих изменений?))

2023-03-01 18:40 UTC, kamenskiyyyy commented on packages/client/src/entities/music/const.ts
> +};
тим лид ударит палкой по рукам)

2023-03-01 18:40 UTC, kamenskiyyyy commented on packages/client/src/entities/music/const.ts
> +};
Да и в реальной компании у разработчика не может быть доступа к проду

2023-03-01 18:48 UTC, kamenskiyyyy commented on packages/client/src/entities/music/const.ts
> +};
Я тебя понял, в любом случае нужна история изменений. Когда на проекте куча людей как у нас важно понимать кто что делал и почему может что-то не работать

2023-03-01 20:43 UTC, DmitryLavrov commented on packages/client/src/entities/music/ui.ts
> +    if (volume <= 0.01) return;
0,01 - это шаг изменения громкости. Громкость меняем от 0 до 1. Видимо 0,01 - самое маленькое значение. Округлять до какого значения?

2023-03-02 05:35 UTC, kamenskiyyyy commented on packages/client/src/entities/music/ui.ts
> +    if (volume <= 0.01) return;
Округлять, чтобы нули после запятой убрать

2023-03-02 05:52 UTC, kamenskiyyyy commented on packages/client/src/entities/music/ui.ts
> +    if (volume <= 0.01) return;
Дим, а я вижу, что там можно и без округления. В пропсах к `Slider` указать `min={0}` и step не указывать, по умолчанию он будет `Integer`

![image](https://user-images.githubusercontent.com/72261703/222342364-28dafce9-41e3-4f60-b86f-22a4eca9f39a.png)

2023-03-02 06:39 UTC, DmitryLavrov commented on packages/client/src/entities/music/ui.ts
> +    if (volume <= 0.01) return;
Я из этого примера и брал.
Посмотрю еще раз позже.
Сейчас делаю слияние ПР.

2023-03-02 06:47 UTC, merged